# spatialdatahub.org/.travis.yml

sudo: required

language:
  - python

matrix:
  include:
    - python: 3.5
      env: SECRET_KEY="secret" CRYPTO_KEY="HsxAfguf_gRBGNx6C5LFv4LikkrhZZsK_zOhuP2-qsc="

    - python: 3.6
      env: SECRET_KEY="secret" CRYPTO_KEY="HsxAfguf_gRBGNx6C5LFv4LikkrhZZsK_zOhuP2-qsc="

    - python: 3.7
      env: SECRET_KEY="secret" CRYPTO_KEY="HsxAfguf_gRBGNx6C5LFv4LikkrhZZsK_zOhuP2-qsc="
      dist: xenial
      sudo: true

install:
  - "pip install -r requirements.txt"

script:
  - "echo 'hey!'"
  - "python manage.py test test.unit_tests --settings=main.settings.dev -v2"

before_deploy: "echo 'ready to deploy'"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "eu-central-1"  
  app: "spatialdatahub" 
  env: "spatialdatahub-dev"
  bucket_name: "elasticbeanstalk-eu-central-1-707675293479"
  on:
    branch: master

after_deploy: "echo 'application deployed'"
